version: '1.0'

services:
  db:
    image: postgres:15-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bood
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
